# CoA (Change of Authorization) / Disconnect Settings

[coa]
enabled = yes
port = 3799

# radclient used for sending CoA/Disconnect from LuCI/web console:
[radclient]
binary = /usr/bin/radclient
timeout = 3
retries = 3
