# Network Interfaces Configuration

[interface "lan"]
device = br-lan
proto = static
ipaddr = 192.168.100.1
netmask = 255.255.255.0

[device "br-lan"]
type = bridge
ports = ens33

[interface "wan"]
device = ens33
proto = dhcp
