# VRRP High Availability Configuration

[global]
enabled = no

[vrrp "instance_1"]
virtual_router_id = 51
interface = ens33
priority = 100
advert_interval = 1

[vip]
addresses = 192.168.100.1/24

[auth]
type = PASS
password = ${RNAS_HA_PASSWORD:-change_me}
