# CoovaChilli Captive Portal Configuration

[global]
enabled = no
interface = br-lan
dhcp_if = br-lan
net = 192.168.182.0/24
uam_server = https://hotspot.rnas.dev
radius_server = 192.168.0.85
radius_secret = ${RNAS_RADIUS_SECRET:-testing123}
