# QoS / Traffic Control Configuration

[global]
enabled = no
algorithm = cake
interface = ens33

[default_class]
rate = 100mbit
ceil = 200mbit

[per_user]
enabled = no
default_rate = 10mbit
default_ceil = 20mbit
radius_attr = WISPr-Bandwidth-Max-Up
